---
- name: run shell
  hosts: nyu
  become: yes
  become_method: sudo
  tasks:
    - name: run command with shell
      shell: ls > log.txt
      #shell: prepareForBehatTests.sh > log.txt
      #register: log
      #args:
        #chdir: /wp/tests/
